# Non Graded Challenge 4
- Muhammad Nafisa Fakhri
- FTDS Batch 013

In [8]:
import numpy as np

1. Pembuatan tensor

In [9]:
tensor = np.array([[[23,50],[7,12]],
                   [[57,67],[99,43]],
                   [[75,21],[57,12]],
                   [[87,26],[18,84]]])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [10]:
tensor.shape

(4, 2, 2)

2. Perkalian matrix dengan matrix menggunakan dot product

In [17]:
a = np.array([[23,50,19],[7,12,109],[57,67,98]])
b = np.array([[17],[22],[19]])

print(a)
print(" ")
print(b)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
 
[[17]
 [22]
 [19]]


In [12]:
a@b # a dot b

array([[1852],
       [2454],
       [4305]])

3. Perhitungan Transpose, Determinan, dan Invers dari matrix

In [13]:
a

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [14]:
a.T # Transpose Matrix a

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [15]:
np.linalg.det(a) # Determinan Matrix a

131344.0000000002

In [16]:
np.linalg.inv(a) # Invers Matrix a

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])