# Non Graded Challenge 5
- Muhammad Nafisa Fakhri
- FTDS Batch 013

In [2]:
import numpy as np

### 1. Penentuan Eigen Vektor

In [3]:
vektor = np.array([1,3])
vektor

array([1, 3])

In [4]:
matrix = np.array([[1,-1],[6,4]])
matrix

array([[ 1, -1],
       [ 6,  4]])

In [16]:
matrix@vektor # Hasil kali matrix dengan vektor

array([-2, 18])

Pertanyaan : Apakah vektor (vektor) termasuk eigen vektor dari (matrix)?

In [6]:
nilai_eigen,vector_eigen = np.linalg.eig(matrix)

print(nilai_eigen)
print(" ")
print(vector_eigen)

[2.5+1.93649167j 2.5-1.93649167j]
 
[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]


In [10]:
nilai_eigen[0]

(2.4999999999999996+1.9364916731037083j)

In [11]:
nilai_eigen[1]

(2.4999999999999996-1.9364916731037083j)

In [18]:
unit_vector1 = np.array([1/np.sqrt(nilai_eigen[0]), 1/np.sqrt(nilai_eigen[0])])
unit_vector1

array([0.53208447-0.1819722j, 0.53208447-0.1819722j])

In [19]:
unit_vector2 = np.array([1/np.sqrt(nilai_eigen[1]), 1/np.sqrt(nilai_eigen[1])])
unit_vector2

array([0.53208447+0.1819722j, 0.53208447+0.1819722j])

In [14]:
reconstruct = vector_eigen @ np.diag(nilai_eigen) @ np.linalg.inv(vector_eigen)
reconstruct

array([[ 1.-4.70796047e-17j, -1.-3.25661782e-18j],
       [ 6.+3.20635860e-16j,  4.-7.82938924e-17j]])

In [20]:
reconstruct@vektor

array([-2.-5.68494582e-17j, 18.+8.57541830e-17j])

Dari perhitungan tersebut diperoleh bahwa hasil rekontruksi dot matrix awal tidak sama dengan rekontrksi matrix akhir, maka dari itu vektor [1,3] bukan eigen vektor dari matrix ([1,-1],[6,4])