# Vector Eigen and Matrix Transformation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
def plot_vector2d(vector2d, origin=[0, 0], **options):
    return plt.arrow(origin[0], origin[1], vector2d[0], vector2d[1],
              head_width=0.2, head_length=0.3, length_includes_head=True,**options)

# Vektor Eigen

In [2]:
a = np.array([[1,2],[2,4]])
a

array([[1, 2],
       [2, 4]])

In [3]:
nilai_eigen,vektor_eigen = np.linalg.eig(a)

In [4]:
nilai_eigen

array([0., 5.])

In [5]:
vektor_eigen # kolom 1 pasangan 0, kolom 2 pasangan 5

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [24]:
# ambil nilai eigen yang tidak nol

unit_vektor = np.array([1/np.sqrt(nilai_eigen[1]),2/np.sqrt(nilai_eigen[1])])
unit_vektor

array([0.4472136 , 0.89442719])

In [7]:
a

array([[1, 2],
       [2, 4]])

In [8]:
vektor = np.array([1,2])
vektor

array([1, 2])

In [9]:
a*vektor

array([[1, 4],
       [2, 8]])

In [10]:
a@vektor

array([ 5, 10])

In [12]:
reconstruct = vektor_eigen @ np.diag(nilai_eigen) @ np.linalg.inv(vektor_eigen)
reconstruct

array([[1., 2.],
       [2., 4.]])

In [23]:
reconstruct@vektor

array([ 5., 10.])

# Contoh Kasus

In [18]:
social_network = np.array([[0,0,0.5,0.5,0,0],
                            [0.25,0,0.25,0.25,0.25,0],
                            [0,0,0,0,0,0],
                            [0.5,0,0,0,0.5,0],
                            [0,0.5,0,0.5,0,0],
                            [0,0,0,0,0,0]])
social_network

array([[0.  , 0.  , 0.5 , 0.5 , 0.  , 0.  ],
       [0.25, 0.  , 0.25, 0.25, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.  , 0.  , 0.  , 0.5 , 0.  ],
       [0.  , 0.5 , 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [22]:
np.linalg.eig(social_network)

(array([ 8.36490824e-01, -7.34808717e-01, -7.60314328e-17, -1.01682107e-01,
         0.00000000e+00,  0.00000000e+00]),
 array([[-3.36698429e-01, -4.68293444e-01, -7.07106781e-01,
         -6.86963150e-01,  4.27796822e-01,  0.00000000e+00],
        [-4.49994361e-01,  1.09959383e-01, -1.99099808e-16,
         -2.73629715e-01,  4.59702715e-01,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  4.59702715e-01,  0.00000000e+00],
        [-5.63290293e-01,  6.88212209e-01,  2.96523080e-17,
          1.39703721e-01, -4.59702715e-01,  0.00000000e+00],
        [-6.05675894e-01, -5.43115217e-01,  7.07106781e-01,
          6.58552413e-01, -4.27796822e-01,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]))

In [19]:
eigen_value, eigen_vector = np.linalg.eig(social_network)

print(eigen_value)
print(" ")
print(eigen_vector)

[ 8.36490824e-01 -7.34808717e-01 -7.60314328e-17 -1.01682107e-01
  0.00000000e+00  0.00000000e+00]
 
[[-3.36698429e-01 -4.68293444e-01 -7.07106781e-01 -6.86963150e-01
   4.27796822e-01  0.00000000e+00]
 [-4.49994361e-01  1.09959383e-01 -1.99099808e-16 -2.73629715e-01
   4.59702715e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.59702715e-01  0.00000000e+00]
 [-5.63290293e-01  6.88212209e-01  2.96523080e-17  1.39703721e-01
  -4.59702715e-01  0.00000000e+00]
 [-6.05675894e-01 -5.43115217e-01  7.07106781e-01  6.58552413e-01
  -4.27796822e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00]]


In [20]:
np.argmax(eigen_value)

0

In [21]:
eigen_vector[2]

array([0.        , 0.        , 0.        , 0.        , 0.45970271,
       0.        ])